//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BannedApiAnalyzer.ApiDesign {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiDesignResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiDesignResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BannedApiAnalyzer.ApiDesign.ApiDesignResources", typeof(ApiDesignResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of banned symbols contains a duplicate..
        /// </summary>
        internal static string DuplicateBannedSymbolDescription {
            get {
                return ResourceManager.GetString("DuplicateBannedSymbolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symbol &apos;{0}&apos; is listed multiple times in the list of banned APIs.
        /// </summary>
        internal static string DuplicateBannedSymbolMessage {
            get {
                return ResourceManager.GetString("DuplicateBannedSymbolMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of banned symbols contains a duplicate.
        /// </summary>
        internal static string DuplicateBannedSymbolTitle {
            get {
                return ResourceManager.GetString("DuplicateBannedSymbolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symbol has been marked as banned in this project, and an alternate should be used instead..
        /// </summary>
        internal static string SymbolIsBannedDescription {
            get {
                return ResourceManager.GetString("SymbolIsBannedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symbol &apos;{0}&apos; is banned in this project{1}.
        /// </summary>
        internal static string SymbolIsBannedMessage {
            get {
                return ResourceManager.GetString("SymbolIsBannedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not used banned APIs.
        /// </summary>
        internal static string SymbolIsBannedTitle {
            get {
                return ResourceManager.GetString("SymbolIsBannedTitle", resourceCulture);
            }
        }
    }
}
